### ISSUE TITLE
Вертикальные видео

### ISSUE THREAD

**Issue by vladislav805** [vladislav805/APIdogChatRobot#4]
* добавить в правила пункт про бан и снятие кармы при отправке вертикальных видео;
* добавить в бота проверку на ориентацию видоса - применять правила, описанное ниже

## Наказание
**Бан**: 24 часа;
**Дельта кармы**: -1280.

## Исключения
* Пересланные сообщения

**Comment by vladislav805** [comment]
Добавлено в правила.

**Comment by BoberMod** [comment]
Я/МЫ apidog
@vladislav805 ущемляет права пользователей своего чата, как это делает кофеинщик

**Comment by vladislav805** [comment]
@BoberMod ЯМЫ на дорогах
